### ISSUE TITLE
No Size or len(set) operation implemented.

### ISSUE THREAD

**Issue by Cing2** [bloeys/nset#2]
Hi,

Cool project you have. The concept of using the bits of integers for containment is really interesting. 
I want to use the project for a small project of mine. However, I miss an operation to get the number of elements in the set. Like set.Size() or using len(set). 

I do not see a way to easily add such a function, as you probably have to search through all buckets. Or a counter should be added to the object to track how many numbers have been added. 

Do you still maintain this project? 
I would be interested to hear from you. 

Thanks

**Comment by bloeys** [comment]
Hey,

Thanks for the interest :) and yes I am still maintaining this project.

Now the only issue with this feature is performance, if we are to do this then I don't want to slow down other functionality. There are two main ways that come to mind:

1. Calculate the number of contained numbers (aka count bits that are 1) every time `.Len()` is called
2. Update a counter every time we add/remove a number

The challenge with the first option is it will be slow in the worst case (set with all uint32 numbers), as that will involve counting how many bits are set in 67M integers. It can be sped up with dedicated CPU instructions that count bits, but still.

We can improve the situation by caching the count and invalidating on each add/remove, but its not a perfect solution.

The second option is ideal if we can do it without introducing major overhead to add/remove/union, ideally adjusting the count without introducing a new branch.

IIRC there is a way to increment/decrement/no-op a value based on just logical conditions and arithmetic, but don't remember it now.

Hopefully Ill have time this week to have a go at option 2 and I'll let you know how it goes.

Thanks

**Comment by Cing2** [comment]
Hey,

Thanks for the reply. 

I would think that the second option add and remove are probably easy and have little impact. The union, I would imagine is more difficult. So for the later it is maybe an idea to use the first option for it. And then you can make it lazy to avoid the overhead. 
But this maybe makes it too complex. 

Curious to hear from you.

Greetings,

**Comment by bloeys** [comment]
Hey,

I was able to implement everything via a live counter without additional branches using some fun bit manipulation and the population count CPU instruction.

I also fixed a nasty bug that happened if you remove an already removed value! (it flipped the value between set/unset :) ).

Things are looking good and performance impact is minimal. I attached benchmarks before and after if you are interested in the [PR](https://github.com/bloeys/nset/pull/3).

The update with the new `.Len()` function is now available in the [new release](https://github.com/bloeys/nset/releases/tag/v1.2.0).

If all is good please close the issue, and thanks for the feature suggestion :)

**Comment by Cing2** [comment]
Hey,

Nice. Cool that you made it work without much overhead. 
I will have a look at the PR.

Thanks for the feature!
